server:
  port: 9000

security:
  sessions: never
  
# tag::secured[]
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password@localhost:8761/eureka/
# end::secured[]
  
spring:
  cloud:
    stream:
      bindings:
        input:
          destination: learning-spring-boot-comments
          group: comments-service
          content-type: application/json
        output:
          destination: learning-spring-boot-chat
          group: comments-chat
          content-type: application/json
