server:
  port: 8200

# tag::security[]
security:
  sessions: never
# end::security[]

# tag::ribbon[]
images:
  commentsUser: user
  commentsPassword: password
# end::ribbon[]

# tag::secured[]
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password@localhost:8761/eureka/
# end::secured[]

spring:
  cloud:
    stream:
      bindings:
        output:
          destination: learning-spring-boot-comments
          group: comments-service
          content-type: application/json
  
