eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  http:
    multipart:
      max-file-size: 10MB
  cloud:
    stream:
      bindings:
        output:
          destination: learning-spring-boot-comments
          group: comments-service
          content-type: application/json
  